apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-kustomization
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/flux-system"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-git-repo
