apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: authority
    istio-injection: enabled
  name: servicey
---
apiVersion: v1
kind: Service
metadata:
  name: servicey
  labels:
    app: servicey
    service: servicey
  namespace: servicey
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: servicey
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicey
  labels:
    account: servicey
  namespace: servicey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicey
  labels:
    app: servicey
    sidecar.istio.io/inject: 'true'
  namespace: servicey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicey
  template:
    metadata:
      labels:
        app: servicey
    spec:
      serviceAccountName: servicey
      containers:
      - name: servicey
        image: alikantunali/s2s:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/kpf/enable-config
          readyOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: cleverbit-config
          items:
          - key: Cleverbit__Enabled
            path: Cleverbit__Enabled
---
