apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1","kind":"GitRepository","metadata":{"annotations":{},"name":"flux-system","namespace":"flux-system"},"spec":{"interval":"1m0s","ref":{"branch":"main"},"url":"ssh://git@github.com/YOUR_ACCOUNT/YOUR_REPO"}}
  creationTimestamp: "2024-04-07T19:41:20Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 2
  name: flux-system
  namespace: flux-system
  resourceVersion: "8082"
  uid: 8fa39966-197b-432b-9331-9b3979703dee
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 60s
  url: ssh://git@github.com/alikantunali/kubernetesTest-main
  secretRef:
    name: flux-system-auth
status:
  conditions:
  - lastTransitionTime: "2024-04-07T20:35:19Z"
    message: building artifact
    observedGeneration: 2
    reason: ProgressingWithRetry
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2024-04-07T20:35:19Z"
    message: 'failed to configure authentication options: invalid ''ssh'' auth option:
      ''identity'' is required'
    observedGeneration: 2
    reason: AuthenticationFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2024-04-07T19:41:32Z"
    message: 'failed to configure authentication options: invalid ''ssh'' auth option:
      ''identity'' is required'
    observedGeneration: 2
    reason: AuthenticationFailed
    status: "True"
    type: FetchFailed
  observedGeneration: -1
