apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: servicex-authorizationpolicy
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/servicex/authorizationpolicy-X
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
