apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: authority
    istio-injection: enabled
  name: servicex
---
apiVersion: v1
kind: Service
metadata:
  name: servicex
  labels:
    app: servicex
    service: servicex
  namespace: servicex
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: servicex
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicex
  labels:
    account: servicex
  namespace: servicex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicex
  labels:
    app: servicex
    sidecar.istio.io/inject: 'true'
  namespace: servicex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicex
  template:
    metadata:
      labels:
        app: servicex
    spec:
      serviceAccountName: servicex
      containers:
      - name: servicex
        image: alikantunali/s2s:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/kpf/enable-config
        - name: cleverbit-secret
          mountPath: /app/kpf/secret
      volumes:
      - name: config-volume
        configMap:
          name: cleverbit-config
          items:
          - key: Cleverbit__Enabled
            path: Cleverbit__Enabled
      - name: cleverbit-secret
        secret:
          secretName: cleverbit-secret





































